return {
  all = "r",
  [ "/" ] = {
    perms = "rwx",
    owner = 0,
    all = "rx",
  },
  [ "/boot" ] = {
    perms = "rwx",
    owner = 0,
    all = "rx",
  },
  [ "/bin" ] = {
    perms = "rwx",
    owner = 0,
    all = "rx",
  },
  [ "/sbin" ] = {
    perms = "rwx",
    owner = 0,
    all = "",
  },
  [ "/lib" ] = {
    perms = "rwx",
    owner = 0,
    all = "rx",
  },
  [ "/opt" ] = {
    perms = "rwx",
    owner = 0,
    all = "rx",
  },
  [ "/dev" ] = {
    perms = "rwx",
    owner = 0,
    all = "rx",
  },
  [ "/proc" ] = {
    perms = "rx",
    owner = 0,
    all = "rx",
  },
  [ "/sys" ] = {
    perms = "rx",
    owner = 0,
    all = "rx",
  },
  [ "/etc" ] = {
    perms = "rwx",
    owner = 0,
    all = "rx",
  },
  [ "/etc/passwd" ] = {
    perms = "rw",
    owner = 0,
    all = "r",
  },
  [ "/etc/group" ] = {
    perms = "rw",
    owner = 0,
    all = "r",
  },
  [ "/etc/shadow" ] = {
    perms = "rw",
    owner = 0,
    all = "",
  },
  [ "/bin/sudo" ] = {
    perms = "rwsx",
    owner = 0,
    all = "rx",
  },
  [ "/bin/passwd" ] = {
    perms = "rwsx",
    owner = 0,
    all = "rx",
  },
  [ "/root" ] = {
    perms = "rwx",
    owner = 0,
    all = "",
  },
  [ "/home" ] = {
    perms = "rwx",
    owner = 0,
    all = "rx",
  },
  [ "/tmp" ] = {
    perms = "rwx",
    owner = 0,
    all = "rwx",
  },
  [ "/var" ] = {
    perms = "rwx",
    owner = 0,
    all = "rwx",
  },
}